### ISSUE TITLE
Discourse Processor

### ISSUE THREAD

**Issue by brew** [okfn/measure#33]
A processor for the Discourse forum. Connected to #3.

Planning to write two separate processors; one for capturing data about a discourse instance, and another to collect data about specified categories.

- [x] A `forums` pipeline to collect data for both a forum instance, and categories within a forum
- [x] A `add_discourse_resource` processor collecting data about a discourse instance at a specific domain [tbc]
  - [x] new users
  - [x] active users (seen within last 24hrs)
  - [x] new posts
  - [x] new topics
  - [x] visits
  - [ ] 10 most active topics
  - [x] tests
  - [x] update schema
  - [x] Update README
- [ ] A `add_discourse_category_resource` processor collecting data about a specific discourse category [tbc]
  - [ ] threads
  - [ ] contributors
  - [ ] posts
  - [ ] likes
  - [ ] views
  - [ ] link_clicks
  - [ ] incoming_links_count
  - [ ] test
  - [ ] update schema
  - [ ] Update README

**Comment by svanderwaal** [comment]
What we're looking to measure: 

1. Newly registered forum users 
2. Active forum users (number of posts increasing in frequency month to month);
3. Which Forum categories create most engagement: 
- # posts per category
- # thread length per forum category (e.g. GODI2016, research and policy, frictionless data)
- Trending topics (quantitative)
* Number of people posting in thread
* Number of viewers
4. Trending topics (qualitative, not a success metric) : 
- Analysis of most-read posts

**Comment by carolsmith123** [comment]
The following article about Discourse Processor is commendable. The following discourse processing is concerned us about the computational processes which are lying under the translation and production of text encompassing more than one sentence.[facebook](https://www.facebook.com/)
