### ISSUE TITLE
Setup OpenFiscal and OKI project configs

### ISSUE THREAD

**Issue by brew** [okfn/measure#37]
- [x] OpenFiscal
- [x] OKI

**Comment by brew** [comment]
@pwalsh @vitorbaptista @jobarratt These two projects are set up with their own configs now. Can I ask project managers (and other interested parties) to review the respective configs to make sure all they want to collect is being collected. Once satisfied this issue can be close.

Configs:
- [OpenFiscal](https://github.com/okfn/measure/blob/2a25c0d65d5874600867da5b02a18abd86e0620a/projects/openfiscal/measure.source-spec.yaml) 
- [OKI](https://github.com/okfn/measure/blob/2a25c0d65d5874600867da5b02a18abd86e0620a/projects/oki/measure.source-spec.yaml)

**Comment by pwalsh** [comment]
@brew yes! Great work.

**Comment by jobarratt** [comment]
This is great @brew i'm not going to share this with Project Managers just yet, because i want to present the whole concept to them first. Planning on doing this as soon as i'm back from Holiday in a few weeks.
