### ISSUE TITLE
Collect data on code libraries from Packagist

### ISSUE THREAD

**Issue by pwalsh** [okfn/measure#39]
A processor to collect `download` data for a php package hosted on Packagist.

- [x] `add_packagist_resource` added to `code-packaging` pipeline
- [x] `downloads`
- [x] tests
- [x] update README
- [x] Update schema

**Comment by brew** [comment]
Daily downloads available from packagist endpoint: `https://packagist.org/packages/frictionlessdata/tableschema/stats/all.json`
