### ISSUE TITLE
Produce final templates for manual forms

### ISSUE THREAD

**Issue by pwalsh** [okfn/measure#4]
# Description

Not all data collection can be automated. We use a set of Google Forms to manually capture such information. Like with the automated collection, there are a set of common form templates that are generally usable across ~any (open data/open source) project, and there is the ability to add custom forms on a per-project basis.

# Tasks

- [x] Create templates for each generic form
- [ ] Write documentation on each generic form, and provide real examples of how and why it looks like it looks

**Comment by jobarratt** [comment]
@brew i've created a template for the outputs tracker https://docs.google.com/a/okfn.org/forms/d/18FXwoPrfRmzYXtbOQVPqtAKqeGm7W3mjAciCCIKsRxU/edit

And also and external outputs tracker

https://docs.google.com/a/okfn.org/forms/d/1BetsHLceiO0Avz2fQR8HmkxIguIZoRMqbzgnMXTe6v4/edit

I think this is all we need for this.

**Comment by jobarratt** [comment]
@brew we need to add an additional field for 'additional information' to each template

**Comment by brew** [comment]
@jobarratt Is 'additional information' an appropriate metric for the Measure database?

**Comment by jobarratt** [comment]
@brew yes, we need to have something to allow an additional level of information. Maybe 'additional information' is not the right thing to call it, but i cant think of anything better.

**Comment by brew** [comment]
I don't mean it shouldn't be added to the form, just that it doesn't seem like something we can make use of in Measure, or visualise in Redash.

**Comment by jobarratt** [comment]
@brew i was thinking if Project managers want a way to include something extra in Redash to give some specific context, that would be viewed in one of the sub dashboards. I know i've not finished my suggestions for these yet but for outputs it is definitely going to include a table and i think this field could be useful.

**Comment by brew** [comment]
@jobarratt That's added now.
