### ISSUE TITLE
Add HubSpot collector

### ISSUE THREAD

**Issue by pwalsh** [okfn/measure#7]
# Description

# Tasks

- [ ] TBD

**Comment by jobarratt** [comment]
From a project point of view, i don't this this is useful and suggest we remove this collector. @pwalsh did you have any specific use cases in mind or thoughts about why this would be useful?

The only thing i can think of would be recording the number of 'leads' which result in 'sales' but i think that it's going to be difficult to tell a useful story with the data.

**Comment by pwalsh** [comment]
WONTFIX. We use hubspot in different ways to what it was designed for, and the value of collecting this data in unclear at present.
